# Generated by Django 5.1.3 on 2025-01-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes_juegos/'),
        ),
    ]
