# Generated by Django 5.1.5 on 2025-01-30 04:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=colorfield.fields.ColorField(default='#313131', image_field=None, max_length=25, samples=None),
        ),
    ]
