# Generated by Django 5.1.5 on 2025-01-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='description',
            new_name='descripcion',
        ),
    ]
