# Generated by Django 5.1.5 on 2025-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_description_customuser_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
