# Generated by Django 5.1.3 on 2025-01-29 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_genero_juego_url_juego_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
