# Generated by Django 5.1.3 on 2025-01-29 04:00

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_juego_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.URLField(blank=True, null=True, validators=[app.validators.validate_image_url]),
        ),
    ]
