# Generated by Django 5.1.3 on 2025-01-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='generos',
        ),
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(choices=[('NULL', 'Género no especificado'), ('ACC', 'Acción'), ('HOR', 'Horror'), ('ADV', 'Aventura'), ('RPG', 'RPG'), ('SIM', 'Simulador'), ('DEP', 'Deportes')], default='NULL', max_length=4),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
