# Generated by Django 5.1.3 on 2025-01-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_juego_generos_juego_genero_delete_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(choices=[('NULL', 'Género no especificado'), ('ACC', 'Acción'), ('HOR', 'Horror'), ('ADV', 'Aventura'), ('RPG', 'RPG'), ('SIM', 'Simulador'), ('DEP', 'Deportes'), ('EST', 'Estrategia'), ('PLT', 'Plataformas'), ('PZL', 'Puzle'), ('CRG', 'Carreras'), ('LCH', 'Lucha'), ('MSO', 'Musical'), ('TIR', 'Tiro'), ('OTR', 'Otros'), ('FIC', 'Ficción interactiva'), ('MMO', 'Multijugador masivo en línea'), ('RTS', 'Estrategia en tiempo real'), ('TAB', 'Juegos de mesa'), ('TRV', 'Trivia'), ('VR', 'Realidad virtual')], default='NULL', max_length=4),
        ),
    ]
